name: ESGVida
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+7

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_editor_plus: ^1.0.6
  screenshot:
    git:
      url: https://github.com/SachinGanesh/screenshot.git



  # Core UI & Navigation
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  lottie: ^3.1.0
  intro_slider: ^4.2.1
  readmore: ^3.0.0
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  emoji_picker_flutter: ^1.6.1
  photo_view: ^0.14.0
  # image_editor_plus: ^1.0.6

  # Media & Camera
  media_picker_widget: ^1.0.7
  photo_manager: ^3.0.0
  camera: ^0.10.5+9
  video_compress: ^3.1.2
  flick_video_player: ^0.8.0
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  # image_editor_plus: ^0.2.4
  social_media_recorder: ^1.1.12

  # File & Storage
  file_picker: ^8.0.6
  open_filex: ^4.4.0 # Better desktop support
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  path: ^1.9.1
  flutter_cache_manager: ^3.3.1

  # Networking & Location
  http: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3

  # Firebase & Notifications
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2

  # Utilities
  uuid: ^4.3.3
  intl: ^0.18.0
  url_launcher: ^6.2.5
  share_plus: ^8.0.2
  stop_watch_timer: ^3.1.1
  record: ^4.4.4
  pdf: ^3.10.8
  printing: ^5.12.0
  device_info_plus: ^9.0.2
  carousel_slider: ^5.0.0
  flutter_chat_ui: ^1.6.5
  flutter_chat_types: ^3.4.3
  pusher_channels_flutter: ^2.2.1
  cached_network_image: ^3.3.1

  # Fonts
  google_fonts: ^6.0.0

  # Screenshot fix for Flutter 3.21+
  # screenshot: 
  #   git:
  #     url: https://github.com/SachinGanesh/screenshot.git
dependency_overrides:
  screenshot:
    git:
      url: https://github.com/SachinGanesh/screenshot.git

  # emoji_picker_flutter: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/error/
    - assets/images/loading/
    - assets/images/shopping/
    - assets/signInImage/
    - assets/messages.json

  fonts:
    - family: Montserrat300
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

    - family: Montserrat400
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

    - family: Montserrat500
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

    - family: Montserrat700
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: forte
      fonts:
        - asset: assets/fonts/fortemtstd.otf
          weight: 500

# name: ESGVida
# description: A new Flutter project.

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version: 1.2.0+7

# environment:
#   sdk: ">=3.1.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.2
#   pusher_channels_flutter: ^2.2.1
#   carousel_slider: ^5.0.0
#   get: ^4.6.6
#   shimmer: ^3.0.0
#   lottie: ^3.1.0
#   permission_handler: ^11.3.1
#   intl: ^0.18.0
#   intro_slider: ^4.2.1
#   shared_preferences: ^2.2.2
#   media_picker_widget: ^1.0.7
#   photo_manager: ^3.0.0
#   camera: ^0.10.5+9
#   stop_watch_timer: ^3.1.1
#   video_compress: ^3.1.2
#   flutter_easyloading: ^3.0.5
#   record: ^4.4.4
#   flick_video_player: ^0.8.0
#   video_player: ^2.8.6
#   readmore: ^3.0.0
#   flutter_chat_ui: ^1.6.10
#   file_picker: ^6.1.1
#   uuid: ^4.3.3
#   open_file: ^3.3.2
#   image_editor_plus: ^0.2.4
  # cached_network_image: ^3.3.1
#   url_launcher: ^6.2.5
#   url_launcher_ios: ^6.2.5
#   flutter_rating_bar: ^4.0.1
#   percent_indicator: ^4.2.3
#   path_provider: ^2.1.2
#   dropdown_button2: ^2.3.9
#   emoji_picker_flutter: ^1.6.1
#   social_media_recorder: ^1.1.12
#   #  ffmpeg_kit_flutter: ^6.0.3-LTS
#   geolocator: ^11.0.0
#   google_maps_flutter: ^2.5.3
#   geocoding: ^3.0.0
#   http: ^1.2.1
#   share_plus: ^8.0.2
#   video_thumbnail: ^0.5.3
#   firebase_messaging: ^14.9.2
#   # device_info_plus: ^8.2.2
#   device_info_plus: ^9.0.2  # or latest version
#   flutter_local_notifications: ^17.1.2
#   webview_flutter: ^4.2.0
#   pdf: ^3.10.8
#   printing: ^5.12.0
#   firebase_core: ^2.31.0
#   flutter_cache_manager: ^3.3.1
#   path: ^1.9.1

#   google_fonts: ^6.0.0 # or your version

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^2.0.0

# #  open_filex: ^4.4.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/
#     - assets/images/
#     - assets/images/error/
#     - assets/images/loading/
#     - assets/images/shopping/
#     - assets/signInImage/
#     - assets/messages.json
#   #   - images/a_dot_ham.jpeg

#   fonts:
#     - family: Montserrat300
#       fonts:
#         - asset: assets/fonts/Montserrat-Light.ttf
#           weight: 300

#     - family: Montserrat400
#       fonts:
#         - asset: assets/fonts/Montserrat-Regular.ttf
#           weight: 400

#     - family: Montserrat500
#       fonts:
#         - asset: assets/fonts/Montserrat-Medium.ttf
#           weight: 500

#     - family: Montserrat700
#       fonts:
#         - asset: assets/fonts/Montserrat-Bold.ttf
#           weight: 700
#     - family: forte
#       fonts:
#         - asset: assets/fonts/fortemtstd.otf
#           weight: 500
