-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrtKbpskdJrIRMg5O
BAoEBA2OcmQskcMyyxRgh2QwxmCgCgYIKoZIzj0DAQehRANCAAT0H4GZY1oTP0nH
om8kNMt6Iq55m+IiwYiUBwMcQ3lNrDckmoUziwQPv1owbBmuieYfsNxaAvmPwCPZ
qXZZcJFH
-----END PRIVATE KEY-----